### ISSUE TITLE
Hlo I'm new here 
I have linux system and I want it look look like amiga os but i dont have any idea how to do it 
Please help me how can i make my linux look like amiga os completely

### ISSUE THREAD

**Issue by Parzivalll23** [lordwolfchild/amigaos_xfwm4_themes#2]

**Comment by lordwolfchild** [comment]
Look, this is a repository for a xfwm4-theme. It is only relevant for you if you want to apply an amigaOS Theme to xfwm4. There is simply no way for me to explain to you here how to achieve what you want, as there are thousands of variables involved which mainly depend on what software you are using. Anyhow, this is not the right place to ask this question. Please google something like "linux desktop themes" as a start and try to learn from there. Closing this issue (as it is not an issue with this project anyway)
